### ISSUE TITLE
Upgrade to newer version of binutils for nightly + musl

### ISSUE THREAD

**Issue by shepmaster** [liuchong/docker-rustup#2]
As mentioned in rust-lang/rust#34978, the Rust-provided MUSL components are now being built with a newer version of binutils, one that is incompatible with the version provided in the current container. The current solution is to upgrade binutils in some fashion. For Ubuntu-based containers, upgrading to 16.04 contains the fixes. I'm not sure what version of Debian will include them.

[An example of output where the versions mismatch](https://travis-ci.org/integer32llc/rust-playground/builds/148764557).

Thanks for all your hard work!

**Comment by liuchong** [comment]
https://github.com/rust-lang/rust-buildbot/pull/110
The above link said the "newer RELX relocation optimizations" been turn off?

😹 Anyway, let's upgrade debian version to "stretch" to solve this problem:

``` text
as -version
GNU assembler (GNU Binutils for Debian) 2.26.1
...
```

**Comment by shepmaster** [comment]
Thank you very much! I've got my code compiling in Travis now!
